# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="domain registration backend"
REPO_LICENSE="GPL-2.0-only"
REPO_TOPICS=""

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/macaw.git"
REPO_WEB_URL="https://github.com/fini-net/macaw"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="macaw"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
)
