//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "billing_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub billing_item_id: i32,
    pub invoice_id: i32,
    pub domain_id: i32,
    #[sea_orm(column_type = "Text")]
    pub item_type: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub unit_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_price: Decimal,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::domains::Entity",
        from = "Column::DomainId",
        to = "super::domains::Column::DomainId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Domains,
    #[sea_orm(
        belongs_to = "super::invoices::Entity",
        from = "Column::InvoiceId",
        to = "super::invoices::Column::InvoiceId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Invoices,
}

impl Related<super::domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Domains.def()
    }
}

impl Related<super::invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
