//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "domain_contacts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub domain_id: i32,
    pub contact_id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub contact_role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contacts::Entity",
        from = "Column::ContactId",
        to = "super::contacts::Column::ContactId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Contacts,
    #[sea_orm(
        belongs_to = "super::domains::Entity",
        from = "Column::DomainId",
        to = "super::domains::Column::DomainId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Domains,
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contacts.def()
    }
}

impl Related<super::domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Domains.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
