//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "invoices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub invoice_id: i32,
    pub customer_id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub invoice_number: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub invoice_date: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub due_date: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub paid_amount: Decimal,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub created_at: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::billing_items::Entity")]
    BillingItems,
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::CustomerId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Customers,
    #[sea_orm(has_many = "super::payments::Entity")]
    Payments,
}

impl Related<super::billing_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillingItems.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
