//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nameservers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub nameserver_id: i32,
    pub domain_id: i32,
    #[sea_orm(column_type = "Text")]
    pub hostname: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub ip_address: Option<String>,
    pub priority: i32,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::domains::Entity",
        from = "Column::DomainId",
        to = "super::domains::Column::DomainId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Domains,
}

impl Related<super::domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Domains.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
